In [80]:
import seaborn as sns

In [81]:
df=sns.load_dataset('tips')

In [82]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [84]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [85]:
df['sex'].value_counts()

sex
Male      157
Female     87
Name: count, dtype: int64

In [86]:
df['smoker'].value_counts()

smoker
No     151
Yes     93
Name: count, dtype: int64

In [87]:
df['day'].value_counts()

day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64

In [88]:
df['time'].value_counts()

time
Dinner    176
Lunch      68
Name: count, dtype: int64

In [89]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [90]:
#Create dependent and independent features
X=df[['tip', 'sex', 'smoker', 'day', 'time', 'size']]
y=df['total_bill']

In [91]:
#split the data into trainig data and test data 
from sklearn.model_selection import train_test_split
X_Train,X_Test,y_train,y_test=train_test_split(X,y,test_size=0.35,random_state=10)

In [92]:
#Features Engineering( Label Encoding => Binary Cat OHE =>multiple cat)
from sklearn.preprocessing import LabelEncoder
le1=LabelEncoder()
le2=LabelEncoder()
le3=LabelEncoder()

In [93]:
X_Train['sex']=le1.fit_transform(X_Train['sex'])
X_Train['smoker']=le2.fit_transform(X_Train['smoker'])
X_Train['time']=le3.fit_transform(X_Train['time'])

In [94]:
X_Test['sex']=le1.transform(X_Test['sex'])
X_Test['smoker']=le2.transform(X_Test['smoker'])
X_Test['time']=le3.transform(X_Test['time'])

In [95]:
X_Train

      tip  sex  smoker   day  time  size
72   3.14    0       1   Sat     0     2
233  1.47    1       0   Sat     0     2
231  3.00    1       1   Sat     0     3
168  1.61    0       1   Sat     0     2
188  3.50    0       1   Sun     0     3
..    ...  ...     ...   ...   ...   ...
64   2.64    1       0   Sat     0     3
15   3.92    1       0   Sun     0     2
228  2.72    1       0   Sat     0     2
125  4.20    0       0  Thur     1     6
9    3.23    1       0   Sun     0     2

[158 rows x 6 columns]

In [96]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [97]:
ct = ColumnTransformer(
    transformers=[
        ('onehot', OneHotEncoder(drop='first', sparse_output=False),
         ['sex','smoker','day','time'])
    ],
    remainder='passthrough'
)

In [98]:
X_Train = ct.fit_transform(X_Train)
X_Test  = ct.transform(X_Test)

In [99]:
X_Train

array([[ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.14,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.47,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  3.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.61,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.5 ,  3.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.5 ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.32,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  4.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.18,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.75,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  5.14,  5.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.07,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.5 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.25,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.56,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.05,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  4.19,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.83,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  4.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  4.73,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.74,  3.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.47,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  5.15,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.23,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.31,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  5.92,  3.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.23,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.88,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.18,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  4.  ,  3.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.54,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  3.4 ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  , 10.  ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.56,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.71,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  4.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.6 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.02,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.  ,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.83,  1.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.03,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  2.5 ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.31,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  7.58,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.48,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.06,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.71,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.44,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.57,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  4.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  5.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.5 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  5.17,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  3.25,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  5.  ,  6.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.24,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  6.5 ,  4.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  4.08,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.27,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.76,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  4.5 ,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  9.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.68,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.61,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  5.6 ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  4.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.25,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  4.3 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.25,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  4.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.  ,  5.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.8 ,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.02,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.2 ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  3.  ,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  0.  ,  3.25,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.  ,  3.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  4.3 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.5 ,  3.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.5 ,  4.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.15,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  3.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  3.  ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.61,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.45,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  6.7 ,  6.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  1.48,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.  ,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  5.  ,  4.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  4.  ,  4.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.92,  1.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.55,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.  ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  3.41,  3.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.58,  2.  ],
       [ 1.  ,  1.  ,  0.  ,  0.  ,  1.  ,  1.  ,  4.  ,  3.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.45,  4.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.98,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.5 ,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  4.29,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  5.85,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  4.34,  4.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.75,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  0.  ,  2.5 ,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.67,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.5 ,  2.  ],
       [ 0.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.  ,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.24,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.01,  2.  ],
       [ 0.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  5.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.96,  2.  ],
       [ 0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  4.67,  3.  ],
       [ 0.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.75,  4.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  3.48,  2.  ],
       [ 1.  ,  1.  ,  1.  ,  0.  ,  0.  ,  0.  ,  1.5 ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  5.  ,  6.  ],
       [ 1.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  2.  ,  2.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  2.55,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.64,  3.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.92,  2.  ],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  0.  ,  2.72,  2.  ],
       [ 0.  ,  0.  ,  0.  ,  0.  ,  1.  ,  1.  ,  4.2 ,  6.  ],
       [ 1.  ,  0.  ,  0.  ,  1.  ,  0.  ,  0.  ,  3.23,  2.  ]])

In [101]:
from sklearn.svm import SVR
svr=SVR()
svr.fit(X_Train,y_train)

SVR()

In [102]:
y_pred=svr.predict(X_Test)

In [104]:
from sklearn.metrics import r2_score
score=r2_score(y_test,y_pred)
print(score)

0.38498149362252143